print("EJERCICIO1")
print("CURSO DE FUNDAMENTOS DE PYTHON")
print("NOMBRE: Carlos Astudillo/n")
a=int(input("Ingrese numero 1 = "))
b=int(input("Ingrese numero 2 = "))
respuesta=a==b
print("/nOPCION 1")
print("Los numeros: "+ str(a) +" y "+ str(b) +" son iguales: "+str(respuesta))
print("OPCION 2")
print(f"Los numeros: {a} y {b} son iguales: {respuesta}")
print("OPCION 3")
print("Los numeros: {} y {} son iguales: {}".format(a,b,respuesta))
print("OPCION 4")
print("Los numeros: ",a,"y",b,"son iguales:",respuesta)
respuesta1=a!=b
print("/nOPCION 1")
print("Los numeros: "+ str(a) +" y "+ str(b) +" son distintos: "+str(respuesta))
print("OPCION 2")
print(f"Los numeros: {a} y {b} son distintos: {respuesta}")
print("OPCION 3")
print("Los numeros: {} y {} son distintos: {}".format(a,b,respuesta))
print("OPCION 4")
print("Los numeros: ",a,"y",b,"son distintos:",respuesta)
respuesta2=a>b
print("/nOPCION 1")
print("Los numeros: "+ str(a) +" y "+ str(b) +" son mayor: "+str(respuesta))
print("OPCION 2")
print(f"Los numeros: {a} y {b} son mayor: {respuesta}")
print("OPCION 3")
print("Los numeros: {} y {} son mayor: {}".format(a,b,respuesta))
print("OPCION 4")
print("Los numeros: ",a,"y",b,"son mayor:",respuesta)
respuesta3=a>=b
print("/nOPCION 1")
print("Los numeros: "+ str(a) +" y "+ str(b) +" mayor o igual: "+str(respuesta))
print("OPCION 2")
print(f"Los numeros: {a} y {b} mayor o igual: {respuesta}")
print("OPCION 3")
print("Los numeros: {} y {} mayor o igual: {}".format(a,b,respuesta))
print("OPCION 4")
print("Los numeros: ",a,"y",b,"mayor o igual:",respuesta)
