a=int(input("Ingrese numero1"))
b=int(input("Ingrese numero2"))
suma=a+b
print("OPCION 1")
print("La suma de: "+ str(a) +" y "+ str(b) +" es: "+str(suma))
print("OPCION 2")
print("La suma de: {a} y {b} es: {suma}")
print("OPCION 3")
print("La suma de: {} y {} es: {}".format(a,b,suma))
print("OPCION 4")
print("La suma de: ",a,"y",b,"es:",suma)
