print("hola mundo")
nombre = input("Ingrese nombre: ")
apellido = input("Ingrese apellido: ")
cedula = input("Ingrese cedula: ")
print("Nombre",nombre,"Apellido",apellido,"Cedula",cedula)
print(nombre*3)
print(len(nombre*3))