numero1=int(input("Ingrese numero 1: "))
numero2=int(input("Ingrese numero 2: "))
print("La suma es:  ", numero1+numero2)
print("La resta es:  ", numero1-numero2)
print("La Multiplicacion es:  ", numero1*numero2)
print("La Division es:  ", numero1/numero2)
print("La Division entera es:  ", numero1//numero2)
print("El modulo es:  ", numero1%numero2)
